///////////////////////////////
CREATE TABLE `fantdraft` (
	`LeagueId` INT(10) NULL DEFAULT NULL,
	`LastChecked` TIMESTAMP NULL DEFAULT NULL,
	`Yr` INT(10) NULL DEFAULT NULL,
	`Round` INT(10) NOT NULL DEFAULT '0',
	`Current` INT(10) NULL DEFAULT '0',
	`Team1` INT(10) NULL DEFAULT NULL,
	`Team2` INT(10) NULL DEFAULT NULL,
	`Team3` INT(10) NULL DEFAULT NULL,
	`Team4` INT(10) NULL DEFAULT NULL,
	`Team5` INT(10) NULL DEFAULT NULL,
	`Team6` INT(10) NULL DEFAULT NULL,
	`Team7` INT(10) NULL DEFAULT NULL,
	`Team8` INT(10) NULL DEFAULT NULL,
	`Team9` INT(10) NULL DEFAULT NULL,
	`Team10` INT(10) NULL DEFAULT NULL,
	`Team11` INT(10) NULL DEFAULT NULL,
	`Team12` INT(10) NULL DEFAULT NULL
)


///////////////////////////////

CREATE TABLE `fantasyusers` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) NOT NULL,
	`Email` VARCHAR(50) NOT NULL,
	`Password` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE
)


///////////////////////////////
CREATE TABLE `fantdraftstatus` (
	`TeamId` INT(10) NULL DEFAULT NULL,
	`Ready` ENUM('Y','N','A') NULL DEFAULT 'N'
)

///////////////////////////////
CREATE TABLE `fantleagues` (
	`LeagueId` INT(10) NOT NULL AUTO_INCREMENT,
	`LeagueName` VARCHAR(50) NOT NULL,
	`CommishId` INT(10) NOT NULL DEFAULT '0',
	`PassYds` INT(10) NOT NULL DEFAULT '0',
	`PassTds` INT(10) NOT NULL DEFAULT '0',
	`PassInts` INT(10) NOT NULL DEFAULT '0',
	`RushYds` INT(10) NOT NULL DEFAULT '0',
	`RushTds` INT(10) NOT NULL DEFAULT '0',
	`RecYds` INT(10) NOT NULL DEFAULT '0',
	`RecTds` INT(10) NOT NULL DEFAULT '0',
	`KORYds` INT(10) NOT NULL DEFAULT '0',
	`KORTds` INT(10) NOT NULL DEFAULT '0',
	`PRYds` INT(10) NOT NULL DEFAULT '0',
	`PRTds` INT(10) NOT NULL DEFAULT '0',
	`Fum` INT(10) NOT NULL DEFAULT '0',
	`FumLost` INT(10) NOT NULL DEFAULT '0',
	`Drafted` ENUM('Y','N','C') NULL DEFAULT 'N',
	`DraftTime` TIMESTAMP NULL DEFAULT NULL,
	`MaxTeams` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`LeagueId`) USING BTREE
)

///////////////////////////////
CREATE TABLE `fantresult` (
	`Week` INT(10) NULL DEFAULT NULL,
	`Team` INT(10) NULL DEFAULT NULL,
	`Score` INT(10) NULL DEFAULT '0'
)

///////////////////////////////
CREATE TABLE `fantschedule` (
	`LeagueId` INT(10) NULL DEFAULT NULL,
	`TeamId` INT(10) NULL DEFAULT NULL,
	`Week1Opp` VARCHAR(50) NULL DEFAULT NULL,
	`Week2Opp` VARCHAR(50) NULL DEFAULT NULL,
	`Week3Opp` VARCHAR(50) NULL DEFAULT NULL,
	`Week4Opp` VARCHAR(50) NULL DEFAULT NULL,
	`Week5Opp` VARCHAR(50) NULL DEFAULT NULL,
	`Week6Opp` VARCHAR(50) NULL DEFAULT NULL,
	`PlayoffWk1Opp` VARCHAR(50) NULL DEFAULT NULL,
	`PlayoffWk2Opp` VARCHAR(50) NULL DEFAULT NULL
)

///////////////////////////////
CREATE TABLE `fantteams` (
	`TeamId` INT(10) NOT NULL AUTO_INCREMENT,
	`LeagueId` INT(10) NULL DEFAULT NULL,
	`OwnerId` INT(10) NULL DEFAULT NULL,
	`TeamName` VARCHAR(50) NULL DEFAULT NULL,
	`Slot1` INT(10) NULL DEFAULT NULL,
	`Slot2` INT(10) NULL DEFAULT NULL,
	`Slot3` INT(10) NULL DEFAULT NULL,
	`Slot4` INT(10) NULL DEFAULT NULL,
	`Slot5` INT(10) NULL DEFAULT NULL,
	`Slot6` INT(10) NULL DEFAULT NULL,
	`Slot7` INT(10) NULL DEFAULT NULL,
	`Slot8` INT(10) NULL DEFAULT NULL,
	`Slot9` INT(10) NULL DEFAULT NULL,
	`Slot10` INT(10) NULL DEFAULT NULL,
	`Wins` INT(10) NULL DEFAULT '0',
	`Losses` INT(10) NULL DEFAULT '0',
	`Ties` INT(10) NULL DEFAULT '0',
	`WinPercent` FLOAT NULL DEFAULT '0',
	`PointsFor` INT(10) NULL DEFAULT '0',
	`PointsAgainst` INT(10) NULL DEFAULT '0',
	PRIMARY KEY (`TeamId`) USING BTREE
)

CREATE TABLE `fantteamsstarters` (
	`LeagueId` INT(10) NULL DEFAULT NULL,
	`TeamId` INT(10) NULL DEFAULT NULL,
	`OwnerId` INT(10) NULL DEFAULT NULL,
	`Qb` INT(10) NULL DEFAULT '0',
	`Rb` INT(10) NULL DEFAULT '0',
	`Wr1` INT(10) NULL DEFAULT '0',
	`Wr2` INT(10) NULL DEFAULT '0',
	`K` INT(10) NULL DEFAULT '0',
	`Flex` INT(10) NULL DEFAULT '0'
)

CREATE TABLE `fanttrades` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`Team1` INT(10) NULL DEFAULT NULL,
	`Team2` INT(10) NULL DEFAULT NULL,
	`Send1` INT(10) NULL DEFAULT NULL,
	`Send2` INT(10) NULL DEFAULT NULL,
	`Send3` INT(10) NULL DEFAULT NULL,
	`Get1` INT(10) NULL DEFAULT NULL,
	`Get2` INT(10) NULL DEFAULT NULL,
	`Get3` INT(10) NULL DEFAULT NULL,
	`Messages` VARCHAR(50) NULL DEFAULT NULL,
	`Approved` ENUM('Y','N','P') NULL DEFAULT 'P',
	PRIMARY KEY (`Id`) USING BTREE
)

CREATE TABLE `fantweek` (
	`CurrentWeek` INT(10) NULL DEFAULT NULL
)

CREATE TABLE `roster` (
	`PlayerId` INT(10) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) NULL DEFAULT NULL,
	`Pos` VARCHAR(50) NULL DEFAULT NULL,
	`Team` VARCHAR(50) NULL DEFAULT NULL,
	`PassYds` INT(10) NOT NULL DEFAULT '0',
	`PassTds` INT(10) NOT NULL DEFAULT '0',
	`Ints` INT(10) NOT NULL DEFAULT '0',
	`RushYds` INT(10) NOT NULL DEFAULT '0',
	`RushTds` INT(10) NOT NULL DEFAULT '0',
	`RecYds` INT(10) NOT NULL DEFAULT '0',
	`RecTds` INT(10) NOT NULL DEFAULT '0',
	`KORYds` INT(10) NOT NULL DEFAULT '0',
	`KORTds` INT(10) NOT NULL DEFAULT '0',
	`PRYds` INT(10) NOT NULL DEFAULT '0',
	`PRTds` INT(10) NOT NULL DEFAULT '0',
	`Fumbles` INT(10) NOT NULL DEFAULT '0',
	`FumblesLost` INT(10) NOT NULL DEFAULT '0',
	`KickPts` INT(10) NOT NULL DEFAULT '0',
	`SoloTkl` INT(10) NOT NULL DEFAULT '0',
	`AssTkl` INT(10) NOT NULL DEFAULT '0',
	`Sacks` INT(10) NOT NULL DEFAULT '0',
	`TFL` INT(10) NOT NULL DEFAULT '0',
	`FF` INT(10) NOT NULL DEFAULT '0',
	`FR` INT(10) NOT NULL DEFAULT '0',
	`DefInts` INT(10) NOT NULL DEFAULT '0',
	`BrUps` INT(10) NOT NULL DEFAULT '0',
	`BlckPunt` INT(10) NOT NULL DEFAULT '0',
	`QBHit` INT(10) NOT NULL DEFAULT '0',
	PRIMARY KEY (`PlayerId`) USING BTREE
)

CREATE TABLE `stats` (
	`PlayerId` INT(10) NULL DEFAULT NULL,
	`Name` VARCHAR(100) NULL DEFAULT NULL,
	`Team` VARCHAR(50) NULL DEFAULT NULL,
	`Pos` VARCHAR(50) NULL DEFAULT NULL,
	`Week` INT(10) NULL DEFAULT NULL,
	`PassYds` INT(10) NULL DEFAULT '0',
	`PassTds` INT(10) NULL DEFAULT '0',
	`Ints` INT(10) NULL DEFAULT '0',
	`RushYds` INT(10) NULL DEFAULT '0',
	`RushTds` INT(10) NULL DEFAULT '0',
	`RecYds` INT(10) NULL DEFAULT '0',
	`RecTds` INT(10) NULL DEFAULT '0',
	`KORYds` INT(10) NULL DEFAULT '0',
	`KORTds` INT(10) NULL DEFAULT '0',
	`PRYds` INT(10) NULL DEFAULT '0',
	`PRTds` INT(10) NULL DEFAULT '0',
	`Fumbles` INT(10) NULL DEFAULT '0',
	`FumblesLost` INT(10) NULL DEFAULT '0',
	`KickPts` INT(10) NULL DEFAULT '0',
	`Fg` INT(10) NULL DEFAULT '0',
	`Xp` INT(10) NULL DEFAULT '0',
	`Rg` INT(10) NULL DEFAULT '0',
	`SoloTkl` INT(10) NULL DEFAULT '0',
	`AssTkl` INT(10) NULL DEFAULT '0',
	`Sacks` INT(10) NULL DEFAULT '0',
	`TFL` INT(10) NULL DEFAULT '0',
	`FF` INT(10) NULL DEFAULT '0',
	`FR` INT(10) NULL DEFAULT '0',
	`DefInts` INT(10) NULL DEFAULT '0',
	`BrUps` INT(10) NULL DEFAULT '0',
	`BlckPunt` INT(10) NULL DEFAULT '0',
	`QBHit` INT(10) NULL DEFAULT '0'
)


CREATE TABLE `rosterchosen` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`LeagueId` INT(10) NULL DEFAULT NULL,
	`TeamId` INT(10) NULL DEFAULT NULL,
	`PlayerId` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`) USING BTREE
)
