<?php
//echo "It's dead";
//die;
	date_default_timezone_set('America/Edmonton');
	require_once("Sql.php");
	require_once("functions.php");


/////////////// copy and paste the array from below //////////////////
	$array = [ 
			];
	$arrayLength = count($array);
        
        $i = 0;
        while ($i < $arrayLength)
        {
            echo $array[$i] ."<br />";
			$Company = $array[$i];
			$Growth = rand(-20,20)/100 + 1;
			$BrandEq = rand(15,50);
			$EarningsPrev =rand(200000,5000000);
			$EarningsCurr = Ceil($EarningsPrev/$Growth);
			$Shares = rand(1,30)*10000;
			$PrevPrice = $EarningsPrev/$Shares + $BrandEq;
            $CurrAss = Ceil(rand(20,70)/10*$EarningsCurr);
            $Inv = rand(70,135)/100*$EarningsCurr; 
            $CurrLiab = Ceil(rand(70,93)/100*$CurrAss);
            $TotAss = Ceil(rand(100,150)/10*$EarningsCurr);
            $TotLiab = Ceil(rand(35,70)/100*$TotAss);
            $EBIT = Ceil(rand(150,195)/100*$EarningsCurr);
            $IntExp = Ceil(rand(30,60)/100*$EarningsCurr);

            echo $EarningsPrev;
			echo " / ";
			echo $Shares;
			echo " = ";
			echo $PrevPrice;


			/////////////// Remember to enter the code //////////////////
			$insertQuery = "INSERT INTO stocks7(Company,PrevPrice,Growth,EarningsCurr,EarningsPrev,Shares,BrandEquity, Sector, CurrAssets, Inventory, CurrLiab, TotAssets, TotLiab, EBITDA, InterestExpense) VALUES (?,?,?,?,?,?,?,'',?,?,?,?,?,?,?)";
			if(ExecuteSqlQuery($insertQuery, $Company,$PrevPrice,$Growth,$EarningsCurr,$EarningsPrev,$Shares, $BrandEq, $CurrAss, $Inv, $CurrLiab, $TotAss, $TotLiab, $EBIT, $IntExp))
			{
				echo "$Company has been placed";
			}
            $i++;


        }

die;


/*
Names/Arrays of Businesses

Code is Ma

'Bluth Company',
'Clint Goodman Construction ',
'Four Aces Construction ',
'Four Aces Dry Wall ',
'Grayson Sky Domes, Ltd.',
'Very Good Building Company ',
'Ace Tomato Company',
'Orlandos',
'Primatech Paper Co.',
'Universal Exports',
'Yoyodyne Propulsion Systems',
'Corley Motors',
'National Motors Corporation',
'Porter Automobiles',
'Powell Motors',
'Vaillante',
'Vapid Motors',
'AALTO Airlines',
'Aeromass',
'Air Israel',
'Air Ixiom',
'Ajira Airways',
'American Travelways Airways',
'Atlantic International Airlines',
'Canada World Airways',
'Columbia Airlines',
'Federation World Airlines',
'Fuji Air',
'Global Airways',
'Grim Reaper Airways',
'Inversion Layer Airlines',
'Mid-Central Airlines',
'Northeast Airlines ',
'Oceanic Airlines',
'Pacific National Airlines',
'Package Air',
'Paradise Airlines',
'Quantum Airlines',
'Sandpiper Air',
'Soar Airlines',
'Stromboli Airlines',
'SunWest Airlines',
'TranCon Airways',
'Trans Allied Airlines',
'Trans American Airlines',
'Trans Continental Airlines',
'Trans Global Airlines',
'Trans Pacific Airlines',
'Trans Regional Airlines',
'Trans United Airways',
'US Midland Air',
'Vole Airlines',
'Wallaby Airlines',
'Windsor Air',
'Yarmy International Airlines',
'Arlesdale Railway',
'Culdee Fell Railway',
'London and West Coast Railway',
'Mid Sodor Railway',
'Northern & Southern Railway',
'Onion Pacific Railroad',
'Skarloey Railway',
'Sodor & Mainland Railway',
'Southern Railway of Northern Ireland',
'Sudden Pacific Railroad',
'Taggart Transcontinental',
'Allied Transamerica',
'FatEx',
'Midnight Express',
'United Delivery Services',
'Universal Containers',
'Worldwide Air Courier'


/////////////////////////////////////////////

Code is Ot

	'Atlantic Corporation',
	'Blaidd Dwrg Nuclear Power Plant',
	'Ewing Oil',
	'Grand Trunk Semaphore Company',
	'McCandless Communications Corporation',
	'Monsters, Incorporated',
	'Parrish Communications',
	'Shelbyville Nuclear Power Plant',
	'Shinra Electric Power Company',
	'Springfield Nuclear Power Plant',
	'Strickland Propane',
	'Waste Disposal',
	'Water & Power Corporation',
	'Dunder Mifflin',
	'Michael Scott Paper Company',
	'Wernham Hogg',
	'United Liberty Paper',
	'Daily Bugle',
	'Daily Planet',
	'Gotham Gazette',
	'Teldar Paper',
	'McMahon and Tate',
	'Parcher and Murphy',
	'Peterson Advertising',
	'Sterling-Cooper',
	'Sloane Curtis Advertising',
	'Zimms',
	'Angel Investigations',
	'Dirk Gentlys Holistic Detective Agency',
	'Psych',
	'Treadstone',
	'World Securities Corporation',
	'Jackman, Carter and Clein',
	'Dewey, Cheathem & Livingstone',
	'Doucette and Stein',
	'Pentex',
	'Get a Move On Removals',
	'Fairview U Move',
	'Planet Express Delivery',
	'IPS Delivery',
	'Meade Publications',
	'Megadodo Publications',
	'Mode Magazine',
	'Goatberger Publishers ',
	'Bad Wolf Corporation',
	'Bada Bing',
	'British Broadcasting Service',
	'DaVille Studio',
	'Dragonfire Films',
	'Hippodrome',
	'Kaiba Corporation',
	'Maroon Cartoons',
	'Network 23',
	'The Tangiers',
	'MeTV',
	'Bettabuys',
	'Crudgington Brewery',
	'Duff Beer',
	'Muffin Buffalo',
	'Soylent Corporation',
	'Stay Puft Corporation',
	'Sunshine Desserts',
	'Big Belly Burger',
	'Big Kahuna Burger',
	'CafÃ© Nervosa',
	'Chotchkies',
	'The Crab Shack',
	'Daddy Greens Pizza',
	'Dixie Pig',
	'The Dot Grill',
	'Doublemeat Palace',
	'Good Burger',
	'Krusty Burger',
	'The Lanford Lunch Box',
	'McDowells',
	'Mels Diner',
	'Milliways',
	'Moobys',
	'Orange Orange',
	'Peach Pit',
	'Rodbells Luncheonette',
	'Burger Shot',
	'Central Perk',
	'The Krusty Krab',
	'Groovy Smoothie',
	'Quake',
	'Quarks Bar & Holding Co.',
	'Mr.Smoothie',
	'The Drunken Clam',
	'The Regal Beagle',
	'Scavos Pizzeria',
	'Rovers Return Inn',
	'The Queen Victoria',
	'The Woolpack',
	'Korova Milkbar',
	'Undercutters Pizza',
	'The Androids Dungeon',
	'Buy More',
	'Curious Goods',
	'Garaks',
	'Frogricks',
	'Hoopers Store',
	'The Magic Box',
	'Try-N-Save',
	'Kwik-E-Mart',
	'Costingtons',
	'Mega Lo Mart',
	'Super Club',
	'Weasleys Wizard Wheezes',
	'Rodbells Department Store',
	'Bergduffs Department Store'


//////////////////////////////////////////////////////////////////

Code is Te

'Dharma Initiative,',
'Ecumena',
'GenTek',
'Hanso Foundation',
'InGen',
'Khumalo',
'Medical Mechanica',
'N.E.R.D.',
'North Central Positronics',
'Prescott Pharmaceuticals',
'Tricell',
'Umbrella Corporation',
'Union Aerospace Corporation',
'VersaLife Corporation',
'Optican',
'Rossum Corporation',
'Simeon',
'Ziodex Industries',
'Monarch',
'Ajax',
'Bonk Business',
'Delos',
'Graystone Industries',
'Cinco',
'Silph Co',
'Allied British Plastics',
'Amalgamated Durables',
'Cymvetica Industries',
'Cym Labs',
'Mainway Toys',
'Ovi Industries',
'Uix Inc',
'Global Chemical Unlimited',
'Paper Street Soap Company',
'Vandelay Industries',
'Wacky Products Incorporated',
'Ware-Armitage Manufacturing Co.',
'W.C. Boggs & Co..',
'Veidt',
'Southport Brickworks',
'Astromech',
'Buy and Large',
'Cyberdyne Systems Corporation',
'Capsule Corporation',
'Enstein Industrial Bionics',
'Mom's Friendly Robot Company',
'Omni Consumer Products',
'Rossum's Universal Robots',
'Sirius Cybernetics Corporation',
'Tyrell Corporation',
'United Robotronics',
'NorthAm Robotics',
'Serrano Genomics',
'Tidis',
'General Products',
'Incom Corporation',
'Nergal Heavy Industries',
'Sienar Fleet Systems',
'Armacham Technology Corporation',
'Initech',
'Caliban Industries',
'Cathedral Software',
'CC Corporation',
'Cogswell Cogs',
'ComTron',
'Contoso and Fabrikam',
'Daystrom Data Concepts',
'ENCOM International',
'Gizmonic Institute',
'Haltmann Works Company',
'Incite Inc.',
'Metacortex',
'Panda Modem',
'Queen Industries',
'Rekall',
'Spaceley's Sprockets',
'Uplink Corporation',
'WarioWare, Inc.',
'Zorin Industries',
'Anaheim Electronics',
'Aperture Science',
'Black Mesa Research Facility',
'ConSec',
'dataDyne',
'Dynatechnics, Inc.',
'Izon',
'MARS Industries',
'Nordyne Defense Dynamics',
'North Osea Grander Industries',
'Office of Scientific Intelligence',
'Seburo',
'Sinclair Solutions',
'Stark Industries',
'Torchwood',
'Zorg Industries'

//////////////////////////////////////////////


Code is Di

'Abstergo Industries',
'Acme Corporation',
'ARCAM Corporation',
'Biffco',
'Binford',
'Blue Sun Corporation',
'Bluecorp',
'CHOAM',
'Conglomerated Amalgamated',
'Conglom-O',
'Cyberdyne Systems',
'Deon International',
'Digivation Industries',
'Edgars Industries',
'Energy Corporation',
'Luxury Corporation',
'Transport Corporation',
'Housing Corporation',
'Food Corporation',
'FrobozzCo International',
'Gadgetron Corporation',
'Global Dynamics',
'Globo-Chem',
'Hishii Industries',
'Interplanetary Expeditions (IPX)',
'Itex.',
'Judgment Six',
'KrebStar',
'LexCorp',
'LuthorCorp',
'Massive Dynamic',
'Matsumura Fishworks',
'Mishima Zaibatsu',
'Momcorp',
'Multi-National United',
'Nakatomi Corporation',
'OsCorp',
'RAMJAC Corporation',
'Sheinhardt Wig Company',
'Tamaribuchi Heavy Manufacturing Concern',
'TetraCorp',
'The Hanso Foundation',
'The Very Big Corporation of America',
'The Zaibatsu Corporation',
'Trade Federation',
'TriOptimum Corporation',
'Ultor Corporation',
'United Northfield/U-North',
'Universal Terraforming',
'Upton-Webber',
'Veridian Dynamics',
'Wayne Enterprises',
'Wesayso Corporation',
'Weyland-Yutani',
'World Company',
'Yotsuba',
'Arctic & European Fish Oil Company',
'Benthic Petroleum',
'Tagruato',
'Czerka Corporation',
'Dinoco',
'Jupiter Mining Corporation',
'Liandri Mining Corporation',
'North Central Positronics',
'Roxxon',
'Slate Rock and Gravel Company',
'Concordance Extraction Corporation',
'Resources Development Administration',
'ORINCO',
'Ellingson Mineral Corporation'


/*